### ISSUE TITLE
APN settings to make a VoLTE call

### ISSUE THREAD

**Issue by akseslab** [herlesupreeth/docker_open5gs#26] opened 2021-02-11 04:08 UTC
Hi Herle, 

I'm using two xiaomi phones with VoLTE enabled on both phones. Both of the phones was succesfully connected to the eNB and already have data connectivity, but when i try to make a phone call, it failed.

My apn settings on both phones is APN: internet, and i was unable to add the second APN:ims. Could you please give some suggestion for this case?

This is my pcap file: https://gofile.io/d/wSiacN

Thanks

**Comment by herlesupreeth** [comment] 2021-02-11 06:52
Hi,

Unfortunately there is not much information in that pcap. Can you please take the pcap from the UE registration?

And for APNs, if by unable to add the ims APN  you mean not visible in APN list then dont worry, its still there but just not visible. Let me know if I understood it correctly

Best Regards,
Supreeth

**Comment by akseslab** [comment] 2021-02-11 10:44
Hi,
[open5gs-volte-call-failed2.zip](https://github.com/herlesupreeth/docker_open5gs/files/5964598/open5gs-volte-call-failed2.zip)

Sorry for the previous incomplete pcap, hope this one is better.
Yes, the APN that i've already set does not visible in the apn list, i was hopping that it will shows:

![apn-on-cellphone](https://user-images.githubusercontent.com/19641669/107626537-8822bb00-6c90-11eb-8f43-54be64d51233.jpg)

in my case, the apn list only shown internet, ims doesn't show up.

Thanks for your help

**Comment by herlesupreeth** [comment] 2021-02-11 12:08
I dont think it matters whether ims APN is shown or not. I see in the pcap attached that UE is trying to register with IMS and IMS has been enabled on the phone

**Comment by akseslab** [comment] 2021-02-11 12:57
So, it's should be OK right?

Could you please show which pcap traffic that shows the UE is trying to register with IMS and IMS has been enabled on the phone?

Thanks

**Comment by herlesupreeth** [comment] 2021-02-11 13:10
> So, it's should be OK right?

Yep

> Could you please show which pcap traffic that shows the UE is trying to register with IMS and IMS has been enabled on the phone?

Pcap in here https://github.com/herlesupreeth/docker_open5gs/issues/26#issuecomment-777355289 . Packet 11836

**Comment by herlesupreeth** [comment] 2021-02-11 13:10
> So, it's should be OK right?

Yep

> Could you please show which pcap traffic that shows the UE is trying to register with IMS and IMS has been enabled on the phone?

Pcap in here https://github.com/herlesupreeth/docker_open5gs/issues/26#issuecomment-777355289 . Packet 11836

**Comment by herlesupreeth** [comment] 2021-02-16 15:20
Close this if the issue is solved

**Closed** 2021-02-18 14:28 UTC
