### ISSUE TITLE
About the settings required for VoLTE

### ISSUE THREAD

**Issue by s5uishida** [herlesupreeth/docker_open5gs#58] opened 2021-10-14 06:49 UTC
Hi @herlesupreeth 

I'm trying VoLTE and please let me ask you a few questions.
I have a plan to use real devices for 4G RAN and smartphones.

If I don't use 5G NFs, are these following changes in the config files enough?

**1) `.env`**
```
DOCKER_HOST_IP
SGWU_ADVERTISE_IP
UPF_ADVERTISE_IP
```
Should the value of `UPF_ADVERTISE_IP` is set to the value of` DOCKER_HOST_IP`?
Also I will change `MCC` and `MNC` in `.env` and `tac` in `mme/mme.yaml`.

**2) Is it OK to uncomment the following for `docker-compose.yaml` and `nsa-deploy.yaml`?**

`mme section`
```
...
    # ports:
    #   - "36412:36412/sctp"
...
```
`sgwu section`
```
...
    # ports:
    #   - "2152:2152/udp"
...
```

**3) I need to edit `sa-deploy.yaml`?**

Thank you very much in advance.

Best regards,

--Shigeru

**Comment by s5uishida** [comment] 2021-10-21 08:02
Hi @herlesupreeth 

I'm sorry for my late response.

After that, I tried various things, but I couldn't find any communication of `Create Bearer Request` or `SIP Registration`. 
Below, I will tell you about this situation.

If you notice anything, I would be greatly appreciated if you could let me know.

**1) Network configuration**
```
  [Real eNodeB]           [Docker Host]
    ---------             -------------
   |         |           |             |
   |         |           |             |
    ---------             -------------
        |                       |
-------------------------------------------------------
       .53                     .7       192.168.66.0/24
```
**2) Configuration file changes**
- `.env` changes
```
--- .env.orig   2021-10-02 18:11:48.000000000 +0000
+++ .env        2021-10-02 22:02:10.000000000 +0000
@@ -1,11 +1,11 @@
 # Set proper timezone to sync times between docker host and containers
 #TZ=Europe/Berlin
 
-MCC=001
-MNC=01
+MCC=441
+MNC=90
 
 TEST_NETWORK=172.22.0.0/24
-DOCKER_HOST_IP=192.168.1.223
+DOCKER_HOST_IP=192.168.66.7
 
 # MONGODB
 MONGO_IP=172.22.0.2
@@ -19,7 +19,7 @@
 # SGW
 SGWC_IP=172.22.0.5
 SGWU_IP=172.22.0.6
-SGWU_ADVERTISE_IP=172.22.0.6
+SGWU_ADVERTISE_IP=192.168.66.7
 
 # SMF
 SMF_IP=172.22.0.7
```
- `fhoss/Dockerfile` changes
```
--- Dockerfile.orig     2021-10-16 21:39:54.000000000 +0000
+++ Dockerfile  2021-10-16 21:53:04.000000000 +0000
@@ -57,7 +57,8 @@
 
 RUN mkdir -p /opt/OpenIMSCore && \
        cd /opt/OpenIMSCore && \
-       git clone https://github.com/herlesupreeth/FHoSS
+       git clone https://github.com/herlesupreeth/FHoSS && \
+       cd FHoSS && git checkout auth_fix_exp && git fetch
 
 ENV JAVA_HOME="/usr/lib/jvm/jdk1.7.0_80"
 ENV CLASSPATH="/usr/lib/jvm/jdk1.7.0_80/jre/lib/"
```
- `docker-compose.yaml` changes (`mme` and `sgwu` sections)
```
--- docker-compose.yaml.orig    2021-10-16 21:48:26.000000000 +0000
+++ docker-compose.yaml 2021-10-21 06:32:58.376737998 +0000
@@ -235,8 +235,8 @@
     expose:
       - "8805/udp"
       - "2152/udp"
-    # ports:
-    #   - "2152:2152/udp"
+    ports:
+      - "2152:2152/udp"
     networks:
       default:
         ipv4_address: ${SGWU_IP}
@@ -352,8 +352,8 @@
       - "5868/sctp"
       - "36412/sctp"
       - "2123/udp"
-    # ports:
-    #   - "36412:36412/sctp"
+    ports:
+      - "36412:36412/sctp"
     networks:
       default:
         ipv4_address: ${MME_IP}
```
- `mme/mme.yaml` changes
```
--- mme.yaml.orig       2021-10-02 18:11:48.000000000 +0000
+++ mme.yaml    2021-10-02 20:56:28.000000000 +0000
@@ -19,7 +19,7 @@
       plmn_id:
         mcc: MCC
         mnc: MNC
-      tac: 1
+      tac: 133
     security:
         integrity_order : [ EIA2, EIA1, EIA0 ]
         ciphering_order : [ EEA0, EEA1, EEA2 ]
```
**3) Open5GS HSS information (IMSI=441900000000511)**

![hss_mask](https://user-images.githubusercontent.com/52230356/138232414-a461ff8a-3302-4148-87ca-75f676408909.png)

**4) FHoSS information (IMSI=441900000000511)**

![fhoss_mask](https://user-images.githubusercontent.com/52230356/138232543-4a7b9c22-1581-4768-bd91-244f1a881d72.png)

**5) Open5GS logs and PCAP files**

On each terminal, I started NFs other than 5GC as follows.
```
docker-compose up mongo mysql dns webui
docker-compose up nrf hss mme pcrf sgwc sgwu smf upf
docker-compose up rtpengine fhoss icscf scscf pcscf
```
After that, I will attach logs of the progress after starting eNodeB and UE.
```
[eNodeB started and connected to EPC]
                |
                v
[UE(smartphone) started and connected to EPC]
                |
                v
[eNodeB reboot unexpectedly]
```

- `open5gs/*.log` [open5gs_log_20211020.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7386980/open5gs_log_20211020.tar.gz)
- pcap on Docker Host/`192.168.66.7` [host_1020_05.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7386985/host_1020_05.pcap.gz)
- pcap on MME/`172.22.0.9` [mme_1020_05.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7386995/mme_1020_05.pcap.gz)

The UE Voice setting was as follows according to the pcap. 
```
Voice Domain Preference and UE's Usage Setting
    Element ID: 0x5d
    Length: 1
    0000 0... = Spare bit(s): 0
    .... .0.. = UE's usage setting: Voice centric
    .... ..11 = Voice domain preference for E-UTRAN: IMS PS voice preferred, CS Voice as secondary (3)
```
I'm also asking the eNodeB vendor about `22. eNB settings` in [VoLTE Setup with Kamailio IMS and Open5GS](https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/).
(According to the eNodeB specifications, it supports VoLTE, so I will expect to be able to use VoLTE.)

If you notice anything, I would be greatly appreciated if you could let me know.

Thank you very much in advance.

Best regards,

--Shigeru

**Comment by herlesupreeth** [comment] 2021-10-21 11:53
> fhoss/Dockerfile changes

These changes is not required imo. Please use the master branch itself

> On each terminal, I started NFs other than 5GC as follows.

This is wrong. Since the docker-compose file has defined dependencies, for e.g. pcrf has dependency on mongo so when you do docker-compose up pcrf it will bring up mongo container as well, so there will be duplication of services. So my suggestion is to run just

`docker-compose up`

the above command will bring up all the required containers

I checked the pcaps and I see attached to 'ims' APN but did not initiate SIP request towards IMS. I would suggest to run the below command on the docker host

`sudo ufw disable`

Your eNB also supports VoLTE no issues there.

A Tip: I see you are using Baicells eNB, just make sure to ask them the latest firmware. I saw this issue of constant reboot and it bricked one eNB

**Comment by s5uishida** [comment] 2021-12-15 12:13
Hi @herlesupreeth 

I haven't resolved the eNodeB restart failure yet, but I got another eNodeB (Baicells) and tried VoLTE on the following IMSI smartphones.

- Phone1) `441900000000511` (phone number: 1511)
- Phone2) `441900000000512` (phone number: 1512)
```
     eNodeB                Docker Host
    ---------             -------------
   |         |           |             |
   |         |           |             |
    ---------             -------------
        |                       |
-------------------------------------------------------
       .53                     .150    192.168.66.0/24
```
In addition, I set the static routing of eNodeB as follows.
```
ip r add 172.22.0.0/24 via 192.168.66.150
```
The SIP Registrations were successful and the IP addresses of the smartphones were assigned as follows.

Phone1)
- internet APN: 192.168.100.2
- ims APN: 192.168.101.2

Phone2)
- internet APN: 192.168.100.3
- ims APN: 192.168.101.3

After that, when I called Phone1-> Phone2, I didn't see the Incoming call on Phone2. Below are pcap and log files from eNodeB startup to smartphone startup and calling.

- open5gs/*.log [open5gs_logs_1215_02.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7719065/open5gs_logs_1215_02.tar.gz)
- pcap on Docker Host/192.168.66.150 [host_1215_02.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7719069/host_1215_02.pcap.gz)
- pcap on MME/172.22.0.9 [mme_1215_02.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7719074/mme_1215_02.pcap.gz)

Looking at `host_1215_02.pcap`, `Create Bearer Request / Response` seems to be successful. But, it became `Status: 408 Request Timeout` as follows.
![reqtimeout](https://user-images.githubusercontent.com/52230356/146181838-01285661-00f4-4f36-ac44-4ec2830c95fe.png)

For your reference, I also attach a screen sorted by Protocol name.
![reqtimeout-sort](https://user-images.githubusercontent.com/52230356/146181962-17bd7cd6-aa7b-4c5a-af72-902267d3059f.png)

Also, when I called self like Phone1-> Phone1, Phone1 became Line busy. The packet at this time was `Status: 486 Busy Here` as follows.
![busy](https://user-images.githubusercontent.com/52230356/146182152-f3d021a6-ec88-461d-9dce-bbc9a7ba627e.png)

For your reference, I also attach a screen sorted by Protocol name.
![busy-sort](https://user-images.githubusercontent.com/52230356/146182203-895ac38c-67fa-4488-b875-9624135a123f.png)

On the other hand, the following logs were output to P-CSCF and I-CSCF. 
```
pcscf        | 98(133) ERROR: <script>: OPTIONS to sip:441900000000511@192.168.101.2:41226 via sip:192.168.101.2:41226;transport=tcp...
pcscf        | 98(133) ERROR: <script>: OPTIONS to sip:441900000000512@192.168.101.3:42666 via sip:192.168.101.3:42666;transport=tcp...
pcscf        | 102(137) ERROR: <script>: request sent to sip:441900000000511@192.168.101.2:41226 completed with code: 200, Type 1
pcscf        | 103(138) ERROR: <script>: request sent to sip:441900000000512@192.168.101.3:42666 completed with code: 200, Type 1
```
```
icscf        |  1(29) ERROR: <script>: $ru => sip:1512@ims.mnc090.mcc441.3gppnetwork.org;user=phone
icscf        |  1(29) INFO: ims_icscf [cxdx_lir.c:69]: create_lia_return_code(): created AVP successfully : [lia_return_code]
icscf        | 10(38) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_experimental_result_code: Failed finding avp
icscf        | 10(38) INFO: ims_icscf [cxdx_lir.c:69]: create_lia_return_code(): created AVP successfully : [lia_return_code]
icscf        |  4(32) ERROR: <script>: $ru => sip:1512@ims.mnc090.mcc441.3gppnetwork.org;user=phone
icscf        |  4(32) INFO: ims_icscf [cxdx_lir.c:69]: create_lia_return_code(): created AVP successfully : [lia_return_code]
icscf        | 13(41) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_experimental_result_code: Failed finding avp
icscf        | 13(41) INFO: ims_icscf [cxdx_lir.c:69]: create_lia_return_code(): created AVP successfully : [lia_return_code]
```

If you notice anything, I would be greatly appreciated if you could let me know.

Thank you very much in advance.

Best regards,

--Shigeru

**Comment by s5uishida** [comment] 2021-12-16 07:14
I will apply the following filter to Wireshark and attach pcap files excluding unnecessary packets.
```
not arp &&
not quic &&
not ip.addr == 192.168.66.28 &&
not ip.addr == 8.8.4.4 &&
not ip.addr == 8.8.8.8 &&
(ip.addr == 192.168.66.0/24 || ip.addr == 172.22.0.0/24 || ip.addr == 192.168.100.0/24 || ip.addr == 192.168.101.0/24) &&
not ip.addr == 142.0.0.0/8 &&
not ip.addr == 210.0.0.0/8 &&
not ip.addr == 64.0.0.0/8 &&
not ip.addr == 216.0.0.0/8 &&
not ip.addr == 34.0.0.0/8 &&
not ip.addr == 54.0.0.0/8 &&
not ip.addr == 218.0.0.0/8 &&
not ip.addr == 172.217.0.0/16
```
- [host_1215_02_small.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7725224/host_1215_02_small.pcap.gz)
- [mme_1215_02_small.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7725228/mme_1215_02_small.pcap.gz)

**Comment by herlesupreeth** [comment] 2021-12-17 12:45
Strange I remember fixing this issue on IMS, its not an issue on the EPC, its either an IMS issue or UE issue. I am referring to the trace you sent earlier "host_1215_02.pcap"

I see the PRACK sent from caller to callee (packts 29497) inside IPSec (correctly) and callee replying with 200 OK for it in packet 29613, however the UE is sending the packet outside of IPSec (wrong). Can you please try with a different phone?

**Comment by herlesupreeth** [comment] 2021-12-17 12:47
Btw, the logs on PCSCF and I-CSCF are normal, they are just printed with wrong logging level, its should have been info level

**Comment by s5uishida** [comment] 2021-12-17 13:26
Hi @herlesupreeth 

Thank you very much for your reply!

The two smartphones used are the following model.

- SHARP AQUOS sense3

Next Monday, I'll try it on the another following model.

- FCNT arrows BZ02

Both of these models are for Japan.

Also, I got it about the P-CSCF and I-CSCF logs.

Thank you very much again!

**Comment by s5uishida** [comment] 2021-12-20 11:36
Hi @herlesupreeth 

I tried VoLTE by inserting the two SIMs of the previous IMSI into the following smartphones.

Phone1) `441900000000511` (phone number: 1511)
- internet APN: 192.168.100.2
- ims APN: 192.168.101.2

Phone2) `441900000000512` (phone number: 1512)
- internet APN: 192.168.100.3
- ims APN: 192.168.101.3

Smartphones are the following model.
- FCNT arrows BZ02

When I called Phone1-> Phone2, I didn't see the Incoming call on Phone2. Below are pcap and log files from eNodeB startup to smartphone startup and calling. I also tried self calling for Phone1-> Phone1.

- open5gs/*.log [open5gs_logs_1220_02.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7744792/open5gs_logs_1220_02.tar.gz)
- pcap on Docker Host/192.168.66.150 [host_1220_02.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7744795/host_1220_02.pcap.gz)
- pcap on MME/172.22.0.9 [mme_1220_02.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7744799/mme_1220_02.pcap.gz)

In `29606`, I found a packet similar to the one you pointed out last time.
![prack](https://user-images.githubusercontent.com/52230356/146758110-b16100ae-2e02-4aef-a591-993a65c1fad4.png)

Also, in `30834`, `Status: 408 Request Timeout` occurred as well.
![timeout](https://user-images.githubusercontent.com/52230356/146758243-689fefd4-06fa-4a15-9a10-d33f584a553f.png)

I disabled (Call settings --> SIP settings -->) `Receive incoming calls` and set `Use SIP calling` to `SIP calls only`.

If there is something wrong with my settings, I would be very glad if you could point it out.

Many thanks!

--Shigeru

**Comment by herlesupreeth** [comment] 2021-12-21 07:49
I would suggest the following, decrease the following value in kamailio_pcscf.cfg to say 1100 and then please re-try calling

https://github.com/herlesupreeth/docker_open5gs/blob/9445dcf1133c0274968373ecdfdff7df73cc5bba/pcscf/kamailio_pcscf.cfg#L136

**Comment by s5uishida** [comment] 2021-12-21 09:37
Hi @herlesupreeth 

Thank you very much for your reply.

I changed `docker_open5gs/pcscf/kamailio_pcscf.cfg` as below, and tried it with the same configuration without changing other settings.
```
udp_mtu = 1000
```
When I called Phone1 -> Phone2, `Status: 408 Request Timeout` did not occur, but the packet of `Status: 500 Server Internal Error` was sent from P-CSCF to S-CSCF as shown below. Also, since `host_1221_01.pcap` size is large, I split it into two files. Please use `mergecap [infile1] [infile2] -w [outfile]` to join them.

- open5gs/*.log [open5gs_logs_1221_01.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7750914/open5gs_logs_1221_01.tar.gz)
- pcap on Docker Host/192.168.66.150 [host_1221_01_div_00000_20211221171642.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7751119/host_1221_01_div_00000_20211221171642.pcap.gz) [host_1221_01_div_00001_20211221172123.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7751123/host_1221_01_div_00001_20211221172123.pcap.gz)
- pcap on MME/172.22.0.9 [mme_1221_01.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7750933/mme_1221_01.pcap.gz)

![500_error](https://user-images.githubusercontent.com/52230356/146902315-82444313-6edb-4502-88ee-e9c49965be5c.png)

Also, when I called self like Phone1-> Phone1, Phone1 became `Busy` as before.

If you notice anything, I would be greatly appreciated if you could let me know.

Best regards,

--Shigeru

**Comment by s5uishida** [comment] 2021-12-22 03:23
I will apply the following filter to Wireshark and attach pcap file excluding unnecessary packets.
(Along with applying this filter, ether type `0x8899` of RRCP(Realtek Remote Control Protocol) was also excluded.)
```
not icmpv6 &&
not arp &&
not ssh &&
not x11 &&
not quic &&
not ip.addr == 192.168.66.28 &&
not ip.addr == 13.0.0.0/8 &&
not ip.addr == 142.0.0.0/8 &&
not ip.addr == 172.217.0.0/16 &&
not ip.addr == 216.0.0.0/8 &&
not ip.addr == 35.0.0.0/8 &&
not ip.addr == 64.0.0.0/8 &&
not ip.addr == 74.0.0.0/8
```
- [host_1221_01_small.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7759751/host_1221_01_small.pcap.gz)

**Comment by s5uishida** [comment] 2021-12-22 04:19
Also, I changed `docker_open5gs/pcscf/kamailio_pcscf.cfg` as below, and tried it with the same configuration without changing other settings.
```
udp_mtu = 1100
```
The result is that a packet with the same `Status: 500 Server Internal Error` was sent from P-CSCF to S-CSCF.

I will apply the following filter to Wireshark and attach pcap files excluding unnecessary packets.
(Along with applying this filter, ether type 0x8899 of RRCP(Realtek Remote Control Protocol) was also excluded.)
```
not icmpv6 &&
not arp &&
not ssh &&
not x11 &&
not quic &&
not ip.addr == 192.168.66.28 &&
not ip.addr == 108.0.0.0/8 &&
not ip.addr == 13.0.0.0/8 &&
not ip.addr == 142.0.0.0/8 &&
not ip.addr == 172.217.0.0/16 &&
not ip.addr == 216.0.0.0/8 &&
not ip.addr == 34.0.0.0/8 &&
not ip.addr == 54.0.0.0/8 &&
not ip.addr == 74.0.0.0/8 &&
not ip.addr == 99.0.0.0/8
```
- [host_1222_01_small.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7759955/host_1222_01_small.pcap.gz)
- [mme_1222_01.pcap.gz](https://github.com/herlesupreeth/docker_open5gs/files/7759959/mme_1222_01.pcap.gz)

**Comment by s5uishida** [comment] 2021-12-22 05:01
The following two ERROR logs was found in P-CSCF. I also attached entire P-SCSF log.
```
pcscf        | 101(135) NOTICE: <script>: PCSCF MT_reply: 
pcscf        |  Destination URI: <null>
pcscf        |  Request URI: <null>
pcscf        | 101(135) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 101(135) NOTICE: <script>: Source IP and Port: (192.168.101.3:41238)
pcscf        |  Route-URI: 
pcscf        | 101(135) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
pcscf        | 101(135) NOTICE: <script>: Contact header: <null>
pcscf        | 101(135) NOTICE: <script>: PCSCF MT_reply: 
pcscf        |  Destination URI: <null>
pcscf        |  Request URI: <null>
pcscf        | 101(135) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 101(135) NOTICE: <script>: Source IP and Port: (192.168.101.3:41238)
pcscf        |  Route-URI: 
pcscf        | 101(135) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
pcscf        | 101(135) NOTICE: <script>: Contact header: <sip:b58df5e6-52be-4e7d-a379-e065639383c7@192.168.101.3:41238>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
pcscf        | 101(135) NOTICE: <script>: PCSCF MT_reply: 
pcscf        |  Destination URI: <null>
pcscf        |  Request URI: <null>
pcscf        | 101(135) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 101(135) NOTICE: <script>: Source IP and Port: (192.168.101.3:41238)
pcscf        |  Route-URI: 
pcscf        | 101(135) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
pcscf        | 101(135) NOTICE: <script>: Contact header: <sip:b58df5e6-52be-4e7d-a379-e065639383c7@192.168.101.3:41238>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
pcscf        | 101(135) ERROR: ims_qos [ims_qos_mod.c:935]: w_rx_aar(): No P-Called-Party hdr found in response. Using req URI from dlg - we shouldn't have to do this101(135) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 1
pcscf        | 94(128) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 7
pcscf        | 108(142) NOTICE: <script>: PCSCF MO_reply: 
pcscf        |  Destination URI: <null>
pcscf        |  Request URI: <null>
pcscf        | 108(142) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 108(142) NOTICE: <script>: Source IP and Port: (172.22.0.20:6060)
pcscf        |  Route-URI: 
pcscf        | 108(142) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
pcscf        | 108(142) NOTICE: <script>: Contact header: <sip:b58df5e6-52be-4e7d-a379-e065639383c7@192.168.101.3:41238;alias=192.168.101.3~41238~2>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
pcscf        | 108(142) INFO: ims_ipsec_pcscf [cmd.c:998]: ipsec_forward(): Destination changed to [2://sip:192.168.101.2:42596;transport=tcp], from [2:6100]
pcscf        | 108(142) ERROR: ims_qos [ims_qos_mod.c:911]: w_rx_aar(): No P-Asserted-Identity hdr found in request. Using From hdr in req - we shouldn't have to do this108(142) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 1
```
- [pcscf_1222_01.log.gz](https://github.com/herlesupreeth/docker_open5gs/files/7760107/pcscf_1222_01.log.gz)

**Comment by herlesupreeth** [comment] 2021-12-29 08:09
@s5uishida regarding the error in pcscf logs, please ignore them. Its not the root cause of the call failing.

IMO it needs fixes in kamailio base code, currently I am bit occupied with day job will let you know once I am able to fix this

**Comment by s5uishida** [comment] 2021-12-29 11:30
Hi @herlesupreeth 

Thank you very much for your efforts!

I am very much looking forward to hearing from you.

In Japan, the unlicensed sXGP (band39 / 1.9GHz) can be used as private LTE, and I have confirmed that data communication is available for Open5GS CUPS-EPC. Also, I was able to use VoIP by referring to section 12 of [VoLTE Setup with Kamailio IMS and Open5GS](https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/). On this case I use Open5GS or WiFi to assign IP addresses to smartphones.

If you have any suggestions for configurations to get logs, please let me know.
(Also, I am on year-end and new year holidays until 5 Jan.)

Thank you very much again!

Best regards,

--Shigeru

**Comment by herlesupreeth** [comment] 2021-12-30 14:17
Regarding the fix for this, I am not sure whether the following fixes it but its worth a try :) 

Please revert back the udp_mtu = 1100 in kamailio_pcscf.cfg and then apply the below patch in pcscf/route/mt.cfg and give it a try. Send me the trace and logs on PCSCF and SCSCF

```
diff --git a/pcscf/route/mt.cfg b/pcscf/route/mt.cfg
index 43bc6fe..40aaebe 100644
--- a/pcscf/route/mt.cfg
+++ b/pcscf/route/mt.cfg
@@ -81,6 +81,9 @@ route[MT_aar_reply]
 # In-Dialog-MT-Requests
 ######################################################################
 route[MT_indialog] {
+    if(!isdsturiset()) {
+        handle_ruri_alias();
+    }
     xnotice("PCSCF MT_indialog: \n Destination URI: $du\n Request URI: $ru\n");
     xnotice("Source IP and Port: ($si:$sp)\n Route-URI: $route_uri\n");
     xnotice("Received IP and Port: ($Ri:$Rp)\n");
```

Happy holidays and new year!!

**Comment by s5uishida** [comment] 2021-12-30 22:25
Hi @herlesupreeth 

OK.

I don't have access to this environment right now, so I'll try it on 6 Jan and send you the logs.

Thank you very much!

--Shigeru

**Comment by s5uishida** [comment] 2022-01-06 06:50
@herlesupreeth Happy new year!

I changed `mt.cfg` and tried `udp_mtu` in `docker_open5gs/pcscf/kamailio_pcscf.cfg` with the following values.
In either case, I couldn't make a call. 

The list of logs is as follows.

```
20220106_XX.tar.gz
---
host_0106_XX.pcap
mme_0106_XX.pcap
open5gs_logs_0106_XX.tar.gz
rtpengine_fhoss_0106_XX.log
icscf_0106_XX.log
scscf_0106_XX.log
pcscf_0106_XX.log
```

- `udp_mtu = 1100` (0106_01)
When I called Phone1 -> Phone2, the packet of `Status: 500 Server Internal Error` was sent from P-CSCF to S-CSCF.
[20220106_01.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7819880/20220106_01.tar.gz)

- `udp_mtu = 1300` (0106_03)
When I called Phone1 -> Phone2, the packet of `Status: 408 Request Timeout` was sent from P-CSCF to S-CSCF.
[20220106_03.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7819885/20220106_03.tar.gz)

- `udp_mtu = 1000` (0106_04)
When I called Phone1 -> Phone2, the packet of `Status: 500 Server Internal Error` was sent from P-CSCF to S-CSCF.
[20220106_04.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7819891/20220106_04.tar.gz)

You can easily see the `*.log` files in color with the `less -R` command.

If you have any suggestions for configurations to get logs, please let me know.

Thank you very much for your efforts!

Best regards,

--Shigeru

**Comment by herlesupreeth** [comment] 2022-01-10 07:42
I will take a look at trace and get back to you. If it requires any changes in source code will do so and let you know. Thanks for testing :)

**Comment by herlesupreeth** [comment] 2022-01-10 11:08
Please use the `fix_buggy_ue_call` branch in this repo and re-compile the kamailio ims base image and give it a try

i.e.

```
cd ../ims_base
docker build --no-cache --force-rm -t docker_kamailio .
```

and then docker-compose up

**Comment by s5uishida** [comment] 2022-01-10 12:30
Hi @herlesupreeth 

I will try it tomorrow and report the results.

Also, is it necessary to change `mt.cfg` as before?

And, is it OK to set `udp_mtu` in `docker_open5gs/pcscf/kamailio_pcscf.cfg` to `1100`?
If I should try other values as well, please let me know.

Thank you very much!

**Comment by herlesupreeth** [comment] 2022-01-10 12:36
> Also, is it necessary to change mt.cfg as before?

Nope, revert  back to original

> And, is it OK to set udp_mtu in docker_open5gs/pcscf/kamailio_pcscf.cfg to 1100?
> If I should try other values as well, please let me know.

Set it back to 1300

**Comment by s5uishida** [comment] 2022-01-10 12:40
Hi @herlesupreeth 

OK.

Thanks!

**Comment by s5uishida** [comment] 2022-01-11 08:15
Hi @herlesupreeth 

I tried the `fix_buggy_ue_call` branch as follows: 

I used original `mt.cfg` as it was, and set the value of `udp_mtu` to the original `1300`.

The version of Open5GS is not the latest version of `main`, but the following version that does not crash PCRF.

- commit `49d9ed03c75e5e8041f5c9668fece1c9215782b8` - `[MME] fix the crash (#1263)`

```
base/Dockerfile
---
-    git checkout main && meson build --prefix=`pwd`/install && \
+    git checkout 49d9ed03c75e5e8041f5c9668fece1c9215782b8 && meson build --prefix=`pwd`/install && \
```

Also, when building, `/open5gs/install/include` was not found and stopped with an error, so I deleted the following line.
```
base/Dockerfile
---
COPY --from=builder /open5gs/install/include /open5gs/install/include
```

The result was that I couldn't make a call.

When I called Phone1 -> Phone2, the packet of `Status: 500 Server Internal Error` was sent from P-CSCF to S-CSCF.

The log file is as follows. The contents of the log file are the same as before.
[20220111-01.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7844677/20220111-01.tar.gz)

If you have any suggestions for configurations to get logs, please let me know.

Thank you very much!

--Shigeru

**Comment by herlesupreeth** [comment] 2022-01-11 09:36
Thank you for testing it out. I beleive the UE has broken implementation, because as per RFC3261, the UE should have sent the PRACK over TCP but sends over UDP (since the UE didnt ask for MTU in PDNConnectivityRequest). The fix i gave was trying to somehow make it work even in the case of broken UE impl. let me take another look whether i can fix it or not.  

![image](https://user-images.githubusercontent.com/4115839/148917511-e539a030-5d24-44aa-a8a8-0b2721c943fb.png)

**Comment by herlesupreeth** [comment] 2022-01-11 13:43
@s5uishida If you dont mind, can you please increase the udp_mtu to 1450 and give it a try and send me the trace and logs. I went through the kamailio code and dont see an easy solution at the moment

**Comment by herlesupreeth** [comment] 2022-01-11 15:51
I pushed one more change to `fix_buggy_ue_call` branch, please take those changes and give it a try tomorrow.

**Comment by s5uishida** [comment] 2022-01-12 01:05
Hi @herlesupreeth 

I was able to make a call! Wonderful!

I set `udp_mtu` to the original `1300`.
Also I use the [issues1313](https://github.com/open5gs/open5gs/tree/issues1313) branch for Open5GS.
(Branch for confirming PCRF crash avoidance)

For your reference, the set of logs is attached below.
[20220112-01.tar.gz](https://github.com/herlesupreeth/docker_open5gs/files/7850778/20220112-01.tar.gz)

Also, I was a little worried about the following log of Open5GS when making a call. 
```
open5gs_0112_01.log
---
smf          | 01/12 00:26:19.757: [smf] ERROR: No need to send 'Update Bearer Request' (../src/smf/binding.c:321)
smf          | 01/12 00:26:19.757: [smf] ERROR: bearer_created:0, qos_presence:0, rule_count:0 (../src/smf/binding.c:322)
```
However, after that, I tried several calls and all calls were successful.

Thank you very much for your efforts!

Many many thanks!!

**Comment by herlesupreeth** [comment] 2022-01-12 04:50
Awesome!! Thank you for testing it out. Regarding the logs in smf, you can ignore them because an AAR is sent when UPDATE SIP message is exchanged and if the flow description are the same as what was there during INVITE and 183 message exchange then an update wont be necessary (as the log says)

**Comment by s5uishida** [comment] 2022-01-12 05:11
Hi @herlesupreeth 

I was able to use VoLTE on the following smartphones that support sXGP in Japan.
Thank you very much.

- SHARP AQUOS sense3
- FCNT arrows BZ02

> But i believe it should be a warning and not an error… need to be fixed in open5gs

As pointed out by you, I think so too.

**Comment by s5uishida** [comment] 2022-01-12 08:11
Hi @herlesupreeth 

BTW, do you have any plans to merge `fix_buggy_ue_call` branch into `master`?

I'm really looking forward to it!

Thank you very much!

**Comment by herlesupreeth** [comment] 2022-01-12 08:35
yep, will do definitely

**Comment by s5uishida** [comment] 2022-01-12 08:38
I'm very glad!

**Comment by s5uishida** [comment] 2022-01-13 01:12
Hi @herlesupreeth 

Now I have confirmed the operation again with the latest `docker_open5gs/master` and `open5gs/main`.

After this, I will close this issue today.

Thank you very much again!

**Comment by herlesupreeth** [comment] 2022-01-13 05:03
Cool!! This issue had been there for quite some time i guess but i couldn’t get to bottom of it due to lack of traces and logs (i could not reproduce this issue at my end), but with traces and logs you sent i was able to solve it. Thanks a lot for your efforts

**Closed** 2022-01-13 12:52 UTC

**Comment by zikkuratti** [comment] 2022-07-06 10:46
its work as DOCKER_HOST_IP=172.17.0.1 and as host 10.10.14.89 in my case and both at the same time!! which is better bro?
