### ISSUE TITLE
Language other than English for SMS!

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#128] opened 2022-10-24 13:58 UTC
Hi
Few commitment back i was able to send non English texts in SMS!
But in this commit(5c674f7cbc540d5f196808de78cbf9c54f48e1e9) which placed under open5gs_hss_cx branch, it wont happen ( i see some weird characters!)

Would you please give me some insights on how to fix this?

Trace & Image:
[WeirdCharacter_SMS.zip](https://github.com/herlesupreeth/docker_open5gs/files/9852257/WeirdCharacter_SMS.zip)

Thanks
Best regards

**Comment by modyngs** [comment] 2022-11-01 13:19
I'm not sure but i guess the UTF-8 on the old repo has changed!

**Comment by herlesupreeth** [comment] 2022-11-02 09:25
The commit you are referring to does not change anything related to SMSC. So I don't think its the cause of the issue you are facing

**Comment by modyngs** [comment] 2022-11-13 15:44
@herlesupreeth That's true!
Its the commit that i tried recently but last time i tested other languages than english was far ago, when u introduced the SMS using osmohlr. i guess it was around this commit 371fbb3d3194c71adeea481f78bdafc463459db1 (April 2022)
Thanks
Best regards

**Comment by modyngs** [comment] 2023-04-08 07:02
Would it be related to this commit?
https://github.com/kamailio/kamailio/commit/f9f16a6c700a7378fc30f6f9c0a767438fc638b9

**Comment by herlesupreeth** [comment] 2023-04-08 11:16
It could be. But I am not knowledgeable in that so cant say for sure.

**Comment by herlesupreeth** [comment] 2023-08-30 09:17
This should be now fixed. Please re-compile kamailio base image and give it a try.

**Comment by b3c3ll** [comment] 2023-09-28 14:06
@herlesupreeth 
Thanks for the work

I just git pull to the cx branch from my old one

**Comment by b3c3ll** [comment] 2023-09-28 14:07
Then gets into 
cd ../ims_base
docker build --no-cache --force-rm -t docker_kamailio .

Thats right?

**Comment by herlesupreeth** [comment] 2023-09-29 06:30
> npm WARN EBADENGINE Unsupported engine {

Its a warning so it can be ignored.

> the old branch was cx on commit https://github.com/herlesupreeth/docker_open5gs/commit/3a2c219f9d965c881d9331a2bdf8c986296b48c8!

Thats an old commit. You need to pull the latest commits and re-compile both docker_open5gs and docker_kamailio base images

**Closed** 2024-01-10 09:49 UTC
